language: php

sudo: false

php:
    - 5.5
    - 5.4
    - 5.3

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=1

# Declare 5.6 beta in test matrix.
# @link https://buddypress.trac.wordpress.org/ticket/5620
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
    include:
        - php: 5.6
          env: WP_VERSION=latest
    allow_failures:
        - php: 5.6
    fast_finish: true

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

    # Set up theme information.
    - theme_slug=$(basename $(pwd))
    - mv $theme_slug /tmp/wordpress/src/wp-content/themes/$theme_slug
    - cd /tmp/wordpress/src/wp-content/themes/

script:
    # Search for PHP syntax errors.
    - find . \( -name '*.php' \) -exec php -lf {} \;
    - phpunit
