language: php

sudo: false

php:
    - 5.5
    - 5.4
    - 5.3

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.0 WP_MULTISITE=0
    - WP_VERSION=4.0 WP_MULTISITE=1

# Declare 5.6 beta in test matrix.
# @link https://buddypress.trac.wordpress.org/ticket/5620
# @link http://docs.travis-ci.com/user/build-configuration/
matrix:
    include:
        - php: 5.6
          env: WP_VERSION=latest
    allow_failures:
        - php: 5.6
    fast_finish: true

before_script:
    - composer require codeclimate/php-test-reporter --dev
    - export CODECLIMATE_REPO_TOKEN=bee8990b32feb362b44d6a3cc883527c13d6ebff66d3ccc262437d5179c50a9a ./vendor/bin/test-reporter
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

    # Set up WordPress installation.
    - export WP_DEVELOP_DIR=/tmp/wordpress/
    - mkdir -p $WP_DEVELOP_DIR
    # Set up theme information.
    - theme_slug=$(basename $(pwd))
    - theme_dir=$WP_DEVELOP_DIR/wp-content/themes/$theme_slug
    - cd ..
    - mv $theme_slug $theme_dir
    - cd $theme_dir

script:
    # Search for PHP syntax errors.
    - find . \( -name '*.php' \) -exec php -lf {} \;
    - phpunit --coverage-clover build/logs/clover.xml
